// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGKMcpCyXC8CDuHcYfkMvEDx15j6UOiO8',
    appId: '1:910925911092:web:c2e5a7e18a4de1b8782661',
    messagingSenderId: '910925911092',
    projectId: 'hellociti-fb247',
    authDomain: 'hellociti-fb247.firebaseapp.com',
    storageBucket: 'hellociti-fb247.appspot.com',
    measurementId: 'G-PB7TVV6Y5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6soJXSWmvvWstMkyb2y_8pLZQMmyFO9k',
    appId: '1:910925911092:android:700b28d7b1af18a7782661',
    messagingSenderId: '910925911092',
    projectId: 'hellociti-fb247',
    storageBucket: 'hellociti-fb247.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BwTjP-ipQd9pAiwXKvkzlisL75xqlS4',
    appId: '1:910925911092:ios:800916a083c9dba3782661',
    messagingSenderId: '910925911092',
    projectId: 'hellociti-fb247',
    storageBucket: 'hellociti-fb247.appspot.com',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BwTjP-ipQd9pAiwXKvkzlisL75xqlS4',
    appId: '1:910925911092:ios:48afd0ebe51e885d782661',
    messagingSenderId: '910925911092',
    projectId: 'hellociti-fb247',
    storageBucket: 'hellociti-fb247.appspot.com',
    iosBundleId: 'com.example.newApp.RunnerTests',
  );
}
